[build.environment]

NODE_VERSION = "12.18.3"
YARN_VERSION = "1.22.4"
NEXT_TELEMETRY_DISABLED = "1"
LISTING_SERVICE_URL = "https://listings-next.bloom.exygy.dev/"

[context.production.environment]
GTM_KEY = "GTM-TBD"

[context.branch-deploy.environment]
GTM_KEY = "GTM-TBD"