version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:current # at some point we can fix to a version if needed
    steps:
      - checkout
      - run:
        name: yarn-update
        command: "yarn install"
      - run:
        name: test
        command: yarn test:shared:ui
      #- run:
      #  name: lint
      #  command: yarn lint:all
