version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:current # at some point we can fix to a version if needed
    steps:
      - checkout
      - run: yarn install
      - run: yarn test:shared:ui
      - run: yarn test:services:listings
      - run: yarn test:apps
      #- run: yarn lint:all
