version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0

executors:
  standard-node:
    docker:
      - image: "cimg/node:18.14.2"
      - image: "cimg/postgres:12.10"
        environment:
          POSTGRES_USER: bloom-ci
          # Never do this in production or with any sensitive / non-test data:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: bloom
  standard-node-new:
    docker:
      - image: "cimg/node:18.14.2"
      - image: "cimg/postgres:12.10"
        environment:
          POSTGRES_USER: bloom-ci
          # Never do this in production or with any sensitive / non-test data:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: bloom_prisma
  cypress-node:
    docker:
      - image: "cypress/base:18.14.1"
      - image: "cimg/postgres:12.10"
        environment:
          POSTGRES_USER: bloom-ci
          # Never do this in production or with any sensitive / non-test data:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: bloom
    environment:
      PORT: "3100"
      EMAIL_API_KEY: "SG.SOME-LONG-SECRET-KEY"
      APP_SECRET: "CI-LONG-SECRET-KEY"
      # DB URL for migration and seeds:
      DATABASE_URL: "postgres://bloom-ci@localhost:5432/bloom"
      # DB URL for the jest tests per ormconfig.test.ts
      TEST_DATABASE_URL: "postgres://bloom-ci@localhost:5432/bloom"
      PARTNERS_PORTAL_URL: "http://localhost:3001"

jobs:
  setup:
    executor: standard-node
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/
  setup-with-new-db:
    executor: standard-node
    steps:
      - checkout
      - run: yarn backend:new:install
      - save_cache:
          key: build-cache-new-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/
  lint:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn lint
  jest-shared-helpers:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn test:shared:helpers
  jest-new-backend:
    executor: standard-node-new
    steps:
      - restore_cache:
          key: build-cache-new-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: DB Setup + New Backend Core Tests
          command: |
            yarn test:backend:new:dbsetup
            yarn test:backend:new
            yarn test:backend:new:e2e
          environment:
            PORT: "3100"
            EMAIL_API_KEY: "SG.SOME-LONG-SECRET-KEY"
            APP_SECRET: "CI-LONG-SECRET-KEY"
            # DB URL for migration and seeds:
            DATABASE_URL: "postgres://bloom-ci@localhost:5432/bloom_prisma"
  build-public:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn build:app:public
  build-partners:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn build:app:partners
  unit-test-partners:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn test:app:partners:unit
  unit-test-public:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn test:app:public:unit

workflows:
  build:
    jobs:
      - setup
      - setup-with-new-db
      - lint:
          requires:
            - setup
      - jest-shared-helpers:
          requires:
            - setup
      - jest-new-backend:
          requires:
            - setup-with-new-db
      - build-public:
          requires:
            - setup
      - unit-test-public:
          requires:
            - setup
      - build-partners:
          requires:
            - setup
      - unit-test-partners:
          requires:
            - setup
      - cypress/run:
          name: "cypress-public"
          requires:
            - setup
          executor: cypress-node
          working_directory: sites/public
          yarn: true
          build: |
            yarn test:backend:core:dbsetup
          start: yarn dev:all-cypress
          wait-on: "http://0.0.0.0:3000"
          store_artifacts: true
      - cypress/run:
          name: "cypress-partners"
          requires:
            - setup
          executor: cypress-node
          working_directory: sites/partners
          yarn: true
          build: |
            yarn test:backend:core:dbsetup
          start: yarn dev:all-cypress
          wait-on: "http://0.0.0.0:3001"
          store_artifacts: true
