version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1
# jobs:
#   build:
#     docker:
#       - image: circleci/node:current # at some point we can fix to a version if needed
#     steps:
#       - checkout
#       - run: yarn install
#       - run: yarn test:shared:ui
#       - run: yarn test:services:listings
#       - cypress/run:
#         start: yarn dev:listings && yarn dev:app:public 
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          working_directory: apps/public
          executor: cypress/base-12-6-0
          yarn: true
          start: yarn dev:all
          wait-on: "http://localhost:3000"  
