version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:current # at some point we can fix to a version if needed
    steps:
      - checkout
      - run: yarn install
      - run: yarn test:shared:ui
      - run: yarn test:services:listings
executors:
  default:
    docker:
      - image: circleci/node:current
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          working_directory: apps/public
          executor: default
          yarn: true
          start: yarn dev:all
          wait-on: "http://localhost:3000"  
      - test
