version: 2.1
orbs:
  cypress: cypress-io/cypress@1
dependencies:
  pre:
    - rm -rf ~/.yarn
    - npm i -g yarn
    - yarn -v
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn
executors:
  default:
    docker:
      - image: circleci/node:current # at some point we can fix to a version if needed
workflows:
  build:
    jobs:
      - cypress/install:
          executor: circleci/node:current
          pre-steps:
            - checkout
            - run: 'yarn install'
      - cypress/run:
          executor: circleci/node:current
          yarn: true
          requires:
            - cypress/install
          start: yarn dev:listings && yarn dev:app:public  

# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1
# jobs:
#   build:
#     docker:
#       - image: circleci/node:current # at some point we can fix to a version if needed
#     steps:
#       - checkout
#       - run: yarn install
#       - run: yarn test:shared:ui
#       - run: yarn test:services:listings
#       - cypress/run:
#         start: yarn dev:listings && yarn dev:app:public 