version: 2.1
orbs:
  cypress: cypress-io/cypress@1

executors:
  cypress-node-12:
    docker:
      - image: "cypress/base:12.14.0"

jobs:
  jest-tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn install
      - run: yarn test:shared:ui
      - run: yarn test:services:listings

workflows:
  build:
    jobs:
      - cypress/run:
          executor: cypress-node-12
          working_directory: apps/public
          yarn: true
          start: yarn dev:all
          wait-on: "http://localhost:3000"
      - jest-tests
