[build.environment]

NODE_VERSION = "12.18.4"
YARN_VERSION = "1.22.4"
NEXT_TELEMETRY_DISABLED = "1"

# reminder: URLs and fragments should *not* have a trailing /
BACKEND_API_BASE = "https://sj.bloom.exygy.dev"
LISTINGS_QUERY = "/listings?jsonpath=%24%5B%3F(%40.buildingAddress.county%3D%3D%22San+Jose%22)%5D""

[context.production.environment]
GTM_KEY = "GTM-W8LH9F9"

[context.branch-deploy.environment]
GTM_KEY = "GTM-KF22FJP"
