[build]

command = "yarn run build"

[build.environment]

NODE_VERSION = "12.18.4"
YARN_VERSION = "1.22.4"
NEXT_TELEMETRY_DISABLED = "1"

# reminder: URLs and fragments should *not* have a trailing /
BACKEND_API_BASE = "https://listings-next.bloom.exygy.dev"
LISTINGS_QUERY = "/listings"