services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      - PORT=${PORT}
    ports:
      - '3101:3101'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
